[build]
  command = "echo 'No site to build, but should build functions'"
  publish = "public"
  functions = "netlify/functions"

[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }
