name: Deploy to Netlify on commits to main
## see: https://github.com/netlify/cli/blob/master/docs/commands/deploy.md

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # - name: Install Dependencies
      #   run: yarn install
      - name: Build functions
        run: make build
      # Deploy the site with netlify-cli
      - name: Deploy Site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify deploy --dir=public --functions=functions --prod
